---
env:
  es2020: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaFeatures:
    jsx: true
  plugins:
    - react
    - jest
    - '@typescript-eslint'
  settings:
    react:
      version: detect
  extends:
    - eslint:recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:react/recommended
    - plugin:jest/recommended
    - prettier
    - prettier/@typescript-eslint
  rules:
    'react/prop-types': off
    '@typescript-eslint/no-unused-vars':
      - 2
      - argsIgnorePattern: '^_'
